---
services: docker

env:
#  - distro: centos7
#  - distro: centos6
#  - distro: fedora27
#  - distro: ubuntu1604
#  - distro: ubuntu1404
#  - distro: ubuntu1204

  - distro: debian10
  - distro: debian9
  - distro: debian8
  - distro: ubuntu1804
  - distro: ubuntu1604

script:
  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=false
  - export DOCKER="docker exec --tty ${container_id} env TERM=xterm"

  # Download test shim.
  - wget -O ${PWD}/tests/test.sh https://raw.githubusercontent.com/ambimax/ansible-testscripts/master/roles/test.sh
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh

  # Check versions
  - ${DOCKER} curl localhost/dashboard/
  - ${DOCKER} curl localhost/dashboard
  - ${DOCKER} curl localhost


after_failure:
  - ${DOCKER} curl localhost
  - ${DOCKER} curl localhost:8080
  - ${DOCKER} cat /etc/traefik/traefik.yml
  - ${DOCKER} cat /etc/traefik/providers.yml


notifications:
  slack: ambimax:2MlPTX9bY9aPxCPhJGxHKIT6
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
